# Exported from Render on 2024-11-08T10:21:44Z
services:
- type: web
  name: Argus
  runtime: python
  repo: https://github.com/ThemeHackers/Argus
  plan: free
  region: frankfurt
  buildCommand: pip install -r requirements.txt
  startCommand: .venv/bin/gunicorn -b 0.0.0.0:$PORT app:app
  healthCheckPath: "/health"
version: "1"
