# Exported from Render on 2024-11-08T08:56:02Z
services:
- type: web
  name: Argus
  runtime: python
  repo: https://github.com/ThemeHackers/Argus
  plan: free
  region: singapore
  buildCommand: pip install -r requirements.txt
  startCommand: .venv/bin/gunicorn -b 0.0.0.0:$PORT app:app
  healthCheckPath: /status
  previews:
    generation: automatic
version: "1"
